/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const AwsAmplifyConfig = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:8edab0c1-8d5c-464f-862a-492ed3f5974b",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_5yDIJRA3H",
    "aws_user_pools_web_client_id": "5n9cpfmb69s4414uvuio7jue3q",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "eu-central-1",
            "maps": {
                "items": {
                    "AWSmap-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "AWSmap-dev"
            }
        }
    }
};
